name: Trigger another build

on:
  workflow_run:
    workflows:
      - "Build"
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - run: env | sort

# event_name: workflow_run
# event.workflow_run.conclusion: success|failure
# event.workflow_run.event: push
# event.workflow_run.head_branch: branch or tag name
# event.workflow_run.head_commit.message: ...
